### ISSUE TITLE
Iso Latin (accented) characters garbled: FIXED

### ISSUE THREAD

**Issue by jwishnie** [adammck/pygsm#1]
please review this commit for merge back into adammck/pygsm

http://github.com/jwishnie/pygsm/commit/f509c7c70825dc589319af7595b1c8f8c1334cfb

The approach is:
1. Set message format to HEX (+CSCS="HEX")
2. Parse all incoming messages with incoming_buffer.decode('hex').decode('raw_unicode_escape') which turns a string of hex letters into a decoded unicode string
3. convert all outgoing text with the reverse out.encode('raw_unicode_escape').encode('hex')

This _might_ even work for full Unicode IF unicode sms are sent UTF8 (dunno if they are)

**Comment by adammck** [comment]
sorry that i missed this one. this has since been addressed by rapidsms/pygsm.
